config/routes.rb
# frozen_string_literal: true

# rubocop:disable Metrics/BlockLength:
Rails.application.routes.draw do
  mount River::Engine, at: '/'

  # require 'sidekiq/web'
  # authenticate :researcher, ->(u) { u.view_sidekiq? } do
  #   mount Sidekiq::Web => '/sidekiq'
  # end

  authenticate :researcher, ->(u) { u.view_pghero? } do
    mount PgHero::Engine, at: 'pghero'
  end

  namespace :api do
    namespace :v1 do
      resources :field_projects, only: %i[show]
      resources :inat_observations, only: %i[index]
      resources :places, only: %i[show] do
        get '/gbif_occurrences', to: 'places#gbif_occurrences'
        get '/kingdom_counts', to: 'places#kingdom_counts'
      end
      get '/places_basic', to: 'places#places_basic'
      get '/places_pour', to: 'places#places_pour'

      resources :primers, only: %i[index]
      resources :research_projects, only: %i[show]
      resources :samples, only: %i[index show] do
        get '/taxa_tree', to: 'samples#taxa_tree'
        get '/taxa_list', to: 'samples#taxa_list'
      end
      get '/basic_samples', to: 'samples#basic_samples'
      resource :samples_search, only: %i[show]
      resource :stats, only: [] do
        get '/home_page', to: 'stats#home_page'
      end
      get '/taxa/next_taxon_id', to: 'taxa#next_taxon_id'
      resources :taxa, only: %i[index show]
      get '/taxa_search', to: 'taxa#taxa_search'

      namespace :research_projects do
        namespace :pillar_point do
          params = { slug: 'pillar-point' }
          get 'area_diversity', defaults: params
          get 'common_taxa_map', defaults: params
          get 'biodiversity_bias', defaults: params
          get 'occurrences', defaults: params
          get 'taxonomy_comparison', defaults: params
          get 'sites', defaults: params
        end

        namespace :la_river do
          params = { slug: ResearchProject::LA_RIVER_PILOT_SLUG }
          get 'area_diversity', defaults: params
          get 'pa_area_diversity', defaults: params
          get 'sampling_types', defaults: params
          get 'detection_frequency', defaults: params
          get 'sites', defaults: params
        end
      end

      namespace :pour do
        resources :occurrences, only: %i[index]
        get '/inat_occurrences', to: 'occurrences#inat_occurrences'
      end
    end
  end
end
# rubocop:enable Metrics/BlockLength:

app/models/sample.rb
# frozen_string_literal: true

class Sample < ApplicationRecord
  include PgSearch
  include InsidePolygon
  include AutoUpdateGeom

  REJECTED_STATUS = %i[rejected duplicate_barcode field_blanks].freeze

  multisearchable against: %i[
    barcode status_cd location field_project_name
    research_projects_names
  ]

  belongs_to :field_project
  has_many :kobo_photos
  has_many :asvs
  has_many :research_project_sources, as: :sourceable
  has_many :research_projects, through: :research_project_sources
  has_many :sample_primers

  validate :unique_approved_barcodes

  scope :la_river, (lambda do
    where(field_project_id: FieldProject.la_river.try(:id))
  end)
  scope :results_completed, -> { where(status_cd: :results_completed) }
  scope :approved, (lambda do
    where("status_cd  = 'approved' OR  status_cd = 'results_completed'")
  end)
  scope :with_coordinates, -> { where('latitude > -1') }

  as_enum :status,
          %i[
            submitted
            approved
            results_completed
            processed_invalid_sample
          ] + REJECTED_STATUS,
          map: :string
  as_enum :substrate, KoboValues::SUBSTRATES, map: :string
  as_enum :habitat, KoboValues::HABITAT, map: :string
  as_enum :depth, KoboValues::DEPTH, map: :string

  def status_display
    status.to_s.tr('_', ' ')
  end

  def field_project_name
    field_project.name
  end

  def inside_california?
    return false if latitude.blank? || longitude.blank?

    california = InsidePolygon::CALIFORNIA
    point = [latitude, longitude]

    inside_polygon(point, california)
  end

  def valid_barcode?
    barcode.match?(/^K\d{4}-L[ABC]-S[123]$/) ||
      barcode.match?(/^K\d{4}-(A1|B2|C3|E4|G5|K6|L7|M8|T9)$/)
  end

  def ph_display
    return if kobo_data['pH'].blank?
    kobo_data['pH'].tr('_', '.')
  end

  def moisture_display
    case kobo_data['Moisture']
    when 'dry' then 'Dry+'
    when 'dry_1' then 'Dry'
    when 'nor' then 'Nor'
    when 'wet' then 'Wet'
    when 'wet_1' then 'Wet+'
    else kobo_data['Moisture']
    end
  end

  # rubocop:disable Metrics/CyclomaticComplexity, Metrics/MethodLength
  def light_display
    case kobo_data['light'] || kobo_data['Light']
    when 'low' then 'Low-'
    when 'low_1' then 'Low'
    when 'low_2' then 'Low+'
    when 'nor' then 'Nor-'
    when 'nor_1' then 'Nor'
    when 'nor_2' then 'Nor+'
    when 'hgh' then 'Hgh-'
    when 'hgh_1' then 'Hgh'
    when 'hgh_2' then 'Hgh+'
    else kobo_data['light'] || kobo_data['Light']
    end
  end
  # rubocop:enable Metrics/CyclomaticComplexity, Metrics/MethodLength

  def research_projects_names
    research_projects.pluck(:name)
  end

  # rubocop:disable Metrics/MethodLength
  def kobo_data_display
    return {} if kobo_data == '{}'

    kobo_data.except(
      '_id',
      '_tags',
      '_uuid',
      '_notes',
      '_status',
      '__version__',
      '_attachments',
      '_geolocation',
      '_submitted_by',
      'formhub/uuid',
      'meta/instanceID',
      '_submission_time',
      '_xform_id_string',
      '_bamboo_dataset_id',
      '_validation_status',
      'Confirm_that_the_bar_barcodes_in_whirlpak',
      'What_type_of_substrate_did_you',
      'Enter_the_sampling_date_and_time',
      'What_is_your_kit_number_e_g_K0021',
      '_1_Plan_and_pack_app_dy_7_Leave_no_trace',
      '_Optional_Regarding_rns_to_share_with_us',
      'Get_the_GPS_Location_e_this_more_accurate',
      'Select_the_match_for_e_dash_on_your_tubes',
      '_Optional_Take_a_ph_ironment_you_sampled',
      'Where_are_you_A_UC_serve_or_in_Yosemite',
      'environment_feature',
      'habitat',
      'depth_your_samples',
      'Do_you_have_a_green_soil_three',
      'Describe_the_environ_tions_from_this_list',
      'Choose_from_common_environment',
      'Which_location_lette_codes_LA_LB_or_LC',
      '_optional_Describe_ou_are_sampling_from',
      'You_re_at_your_first_r_barcodes_S1_or_S2',
      '_optional_What_dept_re_your_samples_from',
      'Light',
      'Moisture',
      'Temperature_Celsius',
      'pH'
    )
  end
  # rubocop:enable Metrics/MethodLength

  # rubocop:disable Metrics/MethodLength
  def csv_data_display
    return {} if csv_data == '{}'
    return {} if csv_data.blank?

    csv_data.except(
      'sample_id',
      'sampling_date',
      'sampling_time',
      'location',
      'latitude',
      'longitude',
      'gps_altitude',
      'gps_precision',
      'substrate',
      'habitat',
      'sampling_depth',
      'environmental_features',
      'environmental_settings',
      'field_notes'
    )
  end
  # rubocop:enable Metrics/MethodLength

  def primers_string
    sample_primers.joins(:primer).select('distinct(primers.name)')
                  .map(&:name).join(', ')
  end

  private

  def unique_approved_barcodes
    return unless status_changed?
    return unless status == :approved

    samples = Sample.where(status_cd: :approved, barcode: barcode)
    return unless samples.count == 1

    errors.add(:unique_approved_barcodes,
               "barcode #{barcode} is already taken")
  end
end

app/controllers/admin/samples_controller.rb
# frozen_string_literal: true

module Admin
  class SamplesController < Admin::ApplicationController
    private

    def resource_params
      clean_array_params
      super
    end

    def clean_array_params
      # NOTE: selectize multi adds '' to the array of values.
      SampleDashboard::ARRAY_FIELDS.each do |f|
        next if params[:sample][f].blank?
        params[:sample][f] = params[:sample][f].reject(&:blank?)
      end
    end
  end
end

app/controllers/api/v1/samples_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class SamplesController < Api::V1::ApplicationController
      before_action :add_cors_headers
      include FilterSamples
      include AsvTreeFormatter

      def index
        render json: {
          samples: { data: samples }
        }, status: :ok
      end

      def basic_samples
        render json: {
          samples: basic_samples_for_map
        }, status: :ok
      end

      def basic_samples_for_map
        @basic_samples_for_map ||= begin
          key = "#{website.cache_key}/basic_samples"
          Rails.cache.fetch(key) do
            cols = %w[id latitude longitude substrate_cd barcode status_cd]
            Sample.select(cols)
                  .where(field_project: FieldProject.la_river)
                  .where(status_cd: %w[approved results_completed])
                  .load
          end
        end
      end

      def show
        render json: {
          sample: { data: sample }
        }, status: :ok
      end

      def taxa_list
        render json: {
          taxa_list: organisms
        }, status: :ok
      end

      def taxa_tree
        render json: {
          taxa_tree: asv_tree_taxa
        }, status: :ok
      end

      private

      # =======================
      # show
      # =======================

      def sample_join_sql
        <<~SQL
          LEFT JOIN research_project_sources  as rps
          ON rps.sourceable_id = samples.id
          AND sourceable_type = 'Sample'
          LEFT JOIN research_projects
          ON research_projects.id = rps.research_project_id
          AND research_projects.published = true
        SQL
      end

      def sample
        @sample ||= begin
          approved_completed_samples.find_by(id: sample_id)
        end
      end

      def sample_id
        params[:id] || params[:sample_id]
      end

      def asv_tree_taxa
        @asv_tree_taxa ||= fetch_asv_tree_for_sample(sample.id)
      end

      # rubocop:disable Metrics/MethodLength
      def organisms_sql
        sql = <<~SQL
          SELECT
          ncbi_divisions.name AS division_name,
          (hierarchy_names ->>'phylum')::text ||'|'||
            (hierarchy ->>'phylum')::text as phylum,
          (hierarchy_names ->>'class')::text ||'|'||
            (hierarchy ->>'class')::text as class,
          (hierarchy_names ->>'order')::text ||'|'||
            (hierarchy ->>'order')::text as order,
          (hierarchy_names ->>'family')::text ||'|'||
            (hierarchy ->>'family')::text as family,
          (hierarchy_names ->>'genus')::text ||'|'||
            (hierarchy ->>'genus')::text as genus,
          (hierarchy_names ->>'species')::text ||'|'||
            (hierarchy ->>'species')::text as species,
          ncbi_nodes.taxon_id, ncbi_nodes.iucn_status,
          rank,
          common_names
          FROM ncbi_nodes
          JOIN asvs ON asvs.taxon_id = ncbi_nodes.taxon_id
          JOIN ncbi_divisions
            ON ncbi_nodes.cal_division_id = ncbi_divisions.id
          WHERE asvs.sample_id = $1
        SQL

        if CheckWebsite.pour_site?
          sql += "AND research_project_id IN #{ResearchProject.la_river_ids}"
        end

        sql + <<~SQL
          GROUP BY ncbi_nodes.taxon_id, ncbi_nodes.iucn_status,
          ncbi_divisions.name
          ORDER BY division_name,
          hierarchy_names ->>'phylum',
          hierarchy_names ->>'class',
          hierarchy_names ->>'order',
          hierarchy_names ->>'family',
          hierarchy_names ->>'genus',
          hierarchy_names ->>'species';
        SQL
      end
      # rubocop:enable Metrics/MethodLength

      def organisms
        @organisms ||= begin
          binding = [[nil, params[:sample_id]]]
          conn.exec_query(organisms_sql, 'q', binding)
        end
      end

      # =======================
      # index
      # =======================

      def samples
        @samples ||= begin
          keyword.present? ? multisearch_samples : cached_samples
        end
      end

      def cached_samples
        key = "#{website.cache_key}/api_samples/#{params_values}"
        Rails.cache.fetch(key) do
          approved_completed_samples.load
        end
      end

      def multisearch_ids
        @multisearch_ids ||= begin
          search_results = PgSearch.multisearch(keyword)
          search_results.pluck(:searchable_id)
        end
      end

      def multisearch_samples
        @multisearch_samples ||= begin
          key = "#{website.cache_key}/api_samples/#{params_values}"
          Rails.cache.fetch(key) do
            approved_completed_samples.where(id: multisearch_ids).load
          end
        end
      end

      def website
        @website = Website.default_site
      end

      def params_values
        params.reject { |k, _v| %w[action controller].include?(k) }
              .values.join('_')
      end

      def keyword
        params[:keyword]&.downcase
      end
    end
  end
end

app/controllers/samples_controller.rb
# frozen_string_literal: true

class SamplesController < ApplicationController
  include CheckWebsite
  include FilterSamples
  layout 'river/application' if CheckWebsite.pour_site?

  def index
    @samples_count = approved_samples_count
    @samples_with_results_count = completed_samples_count
    @taxa_count = Website.default_site.taxa_count
  end

  def show
    @division_counts = division_counts
    @sample = sample
    @organisms_count = organisms_count
  end

  private

  # =======================
  # show
  # =======================

  def organisms_count_sql
    <<~SQL
      SELECT count(*) FROM (
        SELECT DISTINCT taxon_id
        FROM asvs
        where sample_id = #{sample.id}
      )as temp;
    SQL
  end

  def organisms_count
    @organisms_count ||= begin
      conn.exec_query(organisms_count_sql).entries.first['count']
    end
  end

  def division_counts_sql
    <<~SQL
      SELECT COUNT(*) AS count_name, name
      FROM asvs
      JOIN ncbi_nodes ON ncbi_nodes.taxon_id = asvs.taxon_id
      JOIN ncbi_divisions ON ncbi_divisions.id = ncbi_nodes.cal_division_id
      WHERE asvs.sample_id = #{sample.id}
      AND ncbi_nodes.taxon_id IN (
        SELECT DISTINCT taxon_id FROM asvs WHERE sample_id = #{sample.id}
      )
      GROUP BY name;
    SQL
  end

  def division_counts
    @division_counts ||= begin
      counts = {}
      conn.exec_query(division_counts_sql).each do |record|
        counts[record['name']] = record['count_name'].to_i
      end
      counts
    end
  end

  def sample
    @sample ||= begin
      temp = approved_completed_samples.find_by(id: params[:id])
      Sample.find(temp&.id)
    end
  end

  def conn
    ActiveRecord::Base.connection
  end
end

app/helpers/samples_helper.rb
# frozen_string_literal: true

module SamplesHelper
  # rubocop:disable Metrics/MethodLength
  def self.taxonomy_string(taxon)
    begin
      hierarchy_names = YAML.safe_load(taxon.hierarchy_names)
    rescue StandardError => _e
      return
    end

    [
      taxon.division_name,
      hierarchy_names['phylum'],
      hierarchy_names['class'],
      hierarchy_names['order'],
      hierarchy_names['family'],
      hierarchy_names['genus'],
      hierarchy_names['species']
    ].compact.join(', ')
  end
  # rubocop:enable Metrics/MethodLength

  # rubocop:disable Metrics/MethodLength
  def self.hierarchy_string(taxon)
    begin
      hierarchy_names = YAML.safe_load(taxon.hierarchy_names)
    rescue StandardError => _e
      return
    end

    {
      kingdom: taxon.division_name,
      phylum: hierarchy_names['phylum'],
      class: hierarchy_names['class'],
      order: hierarchy_names['order'],
      family: hierarchy_names['family'],
      genus: hierarchy_names['genus'],
      species: hierarchy_names['species']
    }.map do |k, v|
      next if v.blank?

      "#{k}: #{v}"
    end.compact.join(', ')
  end
  # rubocop:enable Metrics/MethodLength

  def self.asvs_count(counts, sample)
    count_data = counts.to_a.select { |c| c['sample_id'] == sample.id }.first
    count_data['count'] if count_data.present?
  end
end

app/views/samples/_fieldwork_details.html.erb
<h2>Fieldwork Details</h2>
<table class="table">
  <% if caledna_site? %>
    <tr>
      <td>Project</td>
      <td><%= link_to sample.field_project.name, field_project_path(sample.field_project) %></td>
    </tr>
  <% end %>
  <tr>
    <td>Barcode</td>
    <td><%= sample.barcode %></td>
  </tr>
  <tr>
    <td>Lat/Long</td>
    <td><%= sample.latitude %>, <%= sample.longitude %></td>
  </tr>
  <tr>
    <td>GPS Precision</td>
    <td><%= sample.gps_precision %></td>
  </tr>
  <tr>
    <td>Altitude</td>
    <td><%= sample.altitude %></td>
  </tr>
  <tr>
    <td>Location</td>
    <td><%= sample.location %></td>
  </tr>
  <tr>
    <td>Collection Date</td>
    <td><%= long_date(sample.collection_date) %></td>
  </tr>
  <tr>
    <td>Submission Date</td>
    <td><%= long_date(sample.submission_date) %></td>
  </tr>
  <tr>
    <td>Field Notes</td>
    <td><%= sample.field_notes %></td>
  </tr>
  <tr>
    <td>Substrate</td>
    <td><%= sample.substrate_cd %></td>
  </tr>
  <% if sample.field_project.single_sample_v2_form? %>
    <tr>
      <td>Habitat</td>
      <td><%= sample.habitat_cd %></td>
    </tr>
    <tr>
      <td>Depth of Sample</td>
      <td><%= sample.depth_cd %></td>
    </tr>
    <tr>
      <td>Environmental Features</td>
      <td><%= sample.environmental_features %></td>
    </tr>
    <tr>
      <td>Environmental Settings</td>
      <td><%= sample.environmental_settings %></td>
    </tr>
  <% end %>
  <tr>
    <td>Soil Meter: Temperature Celsius</td>
    <td><%= sample.kobo_data['Temperature_Celsius'] %></td>
  </tr>
  <tr>
    <td>Soil Meter: PH</td>
    <td><%= sample.ph_display %></td>
  </tr>
  <tr>
    <td>Soil Meter: Moisture</td>
    <td><%= sample.moisture_display %></td>
  </tr>
  <tr>
    <td>Soil Meter: Light</td>
    <td><%= sample.light_display %></td>
  </tr>
  <tr>
    <td>Purple Meter: Temperature Celsius</td>
    <td><%= sample.kobo_data['Temperature_Celsius_001'] %></td>
  </tr>
  <tr>
    <td>Purple Meter: Total Dissolved_Solids TDS</td>
    <td><%= sample.kobo_data['Total_Dissolved_Solids_TDS'] %></td>
  </tr>
  <tr>
    <td>Yellow Meter: PH</td>
    <td><%= sample.kobo_data['Record_pH'] %></td>
  </tr>
  <% sample.kobo_data_display.each do |data| %>
    <tr>
      <td><%= data.first.tr('_', ' ') %></td>
      <td><%= data.second %></td>
    </tr>
  <% end %>

  <% sample.csv_data_display.each do |data| %>
    <tr>
      <td><%= data.first.tr('_', ' ') %></td>
      <td><%= data.second %></td>
    </tr>
  <% end %>
</table>

app/views/samples/_list.html.erb
<table class="table">
  <tr>
    <th>Site</th>
    <th>Latitude/Longitude; GPS Precision</th>
    <th>Location</th>
    <th>Status</th>
    <th>Organisms from ASV</th>
  </tr>

  <% samples.each do |sample| %>
    <tr class="clickable_row" data-path="<%= sample_path(sample) %>">
      <td><%= link_to sample.barcode, sample_path(sample) %></td>
      <td>
        <%= sample.latitude %>, <%= sample.longitude %>; <%= sample.gps_precision %>
      </td>
      <td><%= sample.location %></td>
      <td><%= sample.status_display %></td>
      <td><%= SamplesHelper.asvs_count(asvs_count, sample) %></td>
    </tr>
  <% end %>
</table>

<%= paginate samples %>

app/views/samples/_organisms.html.erb
<h2><%= organisms.length %> Organisms from ASVs</h2>

<ul>
<% SamplesHelper.sorted_taxa(organisms).each do |organism| %>
  <li>
    <%= organism['rank']  %>:
    <% if SamplesHelper.threatened?(organism['iucn_status']) %>
      (Name not shown because this species is <%= organism['iucn_status'] %>)
    <% else %>
      <%= link_to organism[:taxonomy_string], taxon_path(organism['taxon_id']) %>
      <%= SamplesHelper.batch_common_names(batch_vernaculars, organism['taxon_id']) %>
    <% end %>
  </li>
<% end %>
</ul>

app/views/samples/_organisms_chart.html.erb
<h2><%= @organisms_count %> Organisms from ASVs</h2>

<p>Click on blue dots to show the children taxa.</p>

<div id="js-asv-tree" class="tree-chart"></div>

app/views/samples/_organisms_list.html.erb
<h2><%= @organisms_count %> Organisms from ASVs</h2>

<div id="js-taxa-list"></div>

app/views/samples/_overview.html.erb
<h2>Overview</h2>
<table class="table">
  <% if caledna_site? %>
    <tr>
      <td>Field Project</td>
      <td><%= link_to sample.field_project.name, field_project_path(sample.field_project) %></td>
    </tr>
  <% end %>
  <tr>
    <td>Research Projects</td>
    <td>
      <% sample.research_projects.each do |project| %>
        <%= link_to project.name, research_project_path(id: project.slug) %>
      <% end %>
    </td>
  </tr>
  <tr>
    <td>Barcode</td>
    <td><%= sample.barcode %></td>
  </tr>
  <tr>
    <td>Lat/Long</td>
    <td>
      <%= sample.latitude %>, <%= sample.longitude %>
    </td>
  </tr>
  <tr>
    <td>Location</td>
    <td><%= sample.location %></td>
  </tr>
  <tr>
    <td>Field Notes</td>
    <td>
      <%= sample.field_notes %>
    </td>
  </tr>
  <tr>
    <td>Status</td>
    <td><%= sample.status_display %></td>
  </tr>
  <tr>
    <td>Collection Date</td>
    <td><%= long_date(sample.collection_date) %></td>
  </tr>
  <% if division_counts.present? %>
  <tr>
   <td>Primers</td>
   <td><%= sample.primers_string %></td>
  </tr>
  <% end %>
</table>

<div class="row">
  <div class="col col-md-6">
    <% if division_counts.present? %>
      <h3><%= @organisms_count %> Organisms from ASVs</h3>
      <canvas id="kingdom-chart" width="400" height="400"></canvas>
    <% end %>
  </div>
  <div class="col col-md-6">
  </div>
</div>

<div class="row">
  <div class="col col-md-6">
    <h3>Map</h3>
    <div id="samples-details-map"></div>
  </div>
  <div class="col col-md-6">
    <h3><%= sample.kobo_photos.load.size %> Site Photos</h3>
    <% if sample.kobo_photos.present? %>
      <%= render partial: "samples/gallery", locals: { kobo_photos: sample.kobo_photos } %>
    <% else %>
      <%= image_tag 'blank_photo.svg' %>
    <% end %>
  </div>
</div>

app/views/samples/_results_metadata.html.erb
<% sample.research_projects.each do |project| %>
  <h2><%= link_to project.name, research_project_path(id: project.slug) %></h2>
  <%= render partial: "research_projects/pages/metadata", locals: { project: project } %>

  <% if  sample.research_project_sources.where(research_project_id: project.id).any? {|s| s.metadata != {} } %>
    <h3>Sample Metadata</h3>
    <table class="table">
      <% sample.research_project_sources.where(research_project_id: project.id).each do |source| %>
        <% source.metadata.each do |field, value| %>
          <tr>
            <td><%= field.tr('_', ' ') %></td>
            <td><%= value %></td>
          </tr>
        <% end %>
      <% end %>
    </table>
  <% end %>

  <hr>
<% end %>

app/views/samples/_summary.html.erb
<table class="table">
  <tr>
    <td>Project</td>
    <td><%= link_to sample.field_data_project.name, field_data_project_path(sample.field_data_project) %></td>
  </tr>
  <tr>
    <td>Barcode</td>
    <td><%= sample.barcode %></td>
  </tr>
  <tr>
    <td>Lat/Long</td>
    <td>
      <%= sample.latitude %>, <%= sample.longitude %>
    </td>
  </tr>
  <tr>
    <td>Status</td>
    <td><%= sample.status_display %></td>
  </tr>
  <tr>
    <td>Collection Date</td>
    <td><%= long_date(sample.submission_date) %></td>
  </tr>

  <% sample.extractions.each do |extraction| %>
   <% if sample.extractions.length > 1%>
      <tr>
        <td><b><%= extraction.extraction_type.name %></b></td>
        <td></td>
      </tr>
    <% end %>
    <tr>
      <td>Analysis Date</td>
      <td><%= long_date(extraction.stat_dna_extraction_date) %></td>
    </tr>
    <tr>
      <td>DNA Results Completed Date</td>
      <td><%= long_date(extraction.stat_dna_extraction_date) %></td>
    </tr>
    <tr>
      <td>Organisms from ASV</td>
      <td>
        <ul>
        <% extraction.asvs.each do |asv| %>
          <li>
            <%= asv.taxon.taxonRank %>:
            <%= link_to asv.taxon.canonicalName, taxon_path(asv.taxon) %>
            <%= asv.taxon.common_names %>
            <% if asv.highlights %>
              <% asv.highlights.each do |highlight| %>
                <br>notes: <%= highlight.notes %>
              <% end %>
            <% end %>

          </li>
        <% end %>
        </ul>
      </td>
    </tr>
  <% end %>
</table>

<%= render partial: "samples/map", locals: { samples: [sample],
  initial_lat: sample.latitude, initial_lng: sample.longitude } %>

app/views/samples/index.html.erb
<h1>Sites <%= " : #{@display_name}" if @display_name %></h1>

<div class="cal-stats-container">
  <ul>
    <li><%= pluralize(number_with_delimiter(@samples_count), 'Site') %></li>
    <li><%= pluralize(number_with_delimiter(@samples_with_results_count), 'Site') %> with results</li>
    <li><%= pluralize(number_with_delimiter(@taxa_count), 'Taxon') %></li>
  </ul>
</div>

<p class="page-description">
  Here's all the soil, sediment, and water samples that were collected in the field and sent
  back to CALeDNA for genetic analyses.
</p>



<div id="samples-map"></div>
<%= javascript_pack_tag 'samples_map' %>
<%= stylesheet_pack_tag 'samples_map'%>